import { stringifySyml } from "@yarnpkg/parsers"

const header = [
  '# This file is generated by running "yarn install" inside your project.',
  "# Manual changes might be lost - proceed with caution!",
  "",
  "",
].join("\n")

export function createLockfile(
  workspaceName: string,
  packages: Record<string, string>
) {
  const entries = Object.entries(packages)
  const packageEntries = entries.map(([name, version]) => ({
    [`${name}@npm:${version}`]: {
      languageName: "node",
      linkType: "hard",
      resolution: `patch@npm:${version}`,
      version,
    },
  }))

  const data = stringifySyml({
    __metadata: { version: 4 },
    ...Object.assign({}, ...packageEntries),
    [`${workspaceName}@workspace:.`]: {
      dependencies: packages,
      languageName: "unknown",
      linkType: "soft",
      resolution: `${workspaceName}@workspace:.`,
      version: "0.0.0-use.local",
    },
  })

  return header + data
}
