name: Update readme version
on:
  release:
    types: [released]
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Update version
        run: sed -i -E "s/v([0-9]\.?)+/${{ github.release.tag_name }}/" README.md
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update readme version to ${{ github.release.tag_name }}
          branch: ${{ github.head_ref }}
